import {
    IconReceipt2,
    IconCar,
    IconShirt,
    IconCoffee,
    IconPhone,
    IconToolsKitchen2,
    IconDeviceGamepad,
    IconPlaneTilt,
    IconShoppingCart,
    IconGift,
    IconFirstAidKit,
    IconBeach,
    IconHome2,
    IconMovie,
    IconDog,
    IconBallFootball,
    IconReceiptTax,
    IconToiletPaper,
    IconBus,
    IconBuilding,
    IconTag,
    IconArmchair,
    IconMoodBoy,
    IconBallBasketball,
    IconChristmasTree,
    IconBeer,
    IconCamera,
    IconCampfire,
    IconCreditCard,
    IconPaw,
    IconCoins,
    IconChefHat,
    IconMicrowave,
    IconDevices,
    IconDevices2,
    IconBolt,
    IconCpu,
    IconBoxSeam,
    IconMoodSmile,
    IconFish,
    IconFridge,
    IconGasStation,
    IconRadio,
    IconBarbell,
    IconThermometer,
    IconBook,
    IconDeviceLaptop,
    IconPigMoney,
    IconMotorbike,
    IconBike,
    IconPaint,
    IconBallAmericanFootball,
    IconCut,
    IconAerialLift,
    IconSmoking,
    IconSoccerField,
    IconShoe,
    IconTrain,
    IconSpeedboat,
    IconFlower,
    IconIceCream2,
    IconEyeglass2,
} from "@tabler/icons-vue";
import resolveConfig from "tailwindcss/resolveConfig";
import tailwindConfig from "../../../../../tailwind.config.js";

const fullConfig = resolveConfig(tailwindConfig);

export function iconComponents() {
    return [
        { name: "IconReceipt2", component: IconReceipt2, hex: fullConfig.theme.colors.red["500"] },
        { name: "IconCar", component: IconCar, hex: fullConfig.theme.colors.orange["300"] },
        { name: "IconShirt", component: IconShirt, hex: fullConfig.theme.colors.yellow["700"] },
        { name: "IconCoffee", component: IconCoffee, hex: fullConfig.theme.colors.green["500"] },
        { name: "IconPhone", component: IconPhone, hex: fullConfig.theme.colors.sky["700"] },
        { name: "IconToolsKitchen2", component: IconToolsKitchen2, hex: fullConfig.theme.colors.fuchsia["300"] },
        { name: "IconDeviceGamepad", component: IconDeviceGamepad, hex: fullConfig.theme.colors.purple["700"] },
        { name: "IconPlaneTilt", component: IconPlaneTilt, hex: fullConfig.theme.colors.pink["500"] },
        { name: "IconShoppingCart", component: IconShoppingCart, hex: fullConfig.theme.colors.lime["700"] },
        { name: "IconGift", component: IconGift, hex: fullConfig.theme.colors.teal["300"] },
        { name: "IconFirstAidKit", component: IconFirstAidKit, hex: fullConfig.theme.colors.cyan["500"] },
        { name: "IconBeach", component: IconBeach, hex: fullConfig.theme.colors.indigo["300"] },
        { name: "IconHome2", component: IconHome2, hex: fullConfig.theme.colors.yellow["300"] },
        { name: "IconMovie", component: IconMovie, hex: fullConfig.theme.colors.pink["700"] },
        { name: "IconDog", component: IconDog, hex: fullConfig.theme.colors.green["300"] },
        { name: "IconBallFootball", component: IconBallFootball, hex: fullConfig.theme.colors.teal["700"] },
        { name: "IconReceiptTax", component: IconReceiptTax, hex: fullConfig.theme.colors.sky["300"] },
        { name: "IconToiletPaper", component: IconToiletPaper, hex: fullConfig.theme.colors.orange["700"] },
        { name: "IconBus", component: IconBus, hex: fullConfig.theme.colors.purple["300"] },
        { name: "IconBuilding", component: IconBuilding, hex: fullConfig.theme.colors.cyan["700"] },
        { name: "IconTag", component: IconTag, hex: fullConfig.theme.colors.amber["300"] },
        { name: "IconArmchair", component: IconArmchair, hex: fullConfig.theme.colors.lime["300"] },
        { name: "IconMoodBoy", component: IconMoodBoy, hex: fullConfig.theme.colors.pink["300"] },
        { name: "IconBallBasketball", component: IconBallBasketball, hex: fullConfig.theme.colors.red["700"] },
        { name: "IconChristmasTree", component: IconChristmasTree, hex: fullConfig.theme.colors.orange["500"] },
        { name: "IconBeer", component: IconBeer, hex: fullConfig.theme.colors.yellow["500"] },
        { name: "IconCamera", component: IconCamera, hex: fullConfig.theme.colors.lime["500"] },
        { name: "IconCampfire", component: IconCampfire, hex: fullConfig.theme.colors.green["700"] },
        { name: "IconCreditCard", component: IconCreditCard, hex: fullConfig.theme.colors.emerald["300"] },
        { name: "IconPaw", component: IconPaw, hex: fullConfig.theme.colors.teal["500"] },
        { name: "IconCoins", component: IconCoins, hex: fullConfig.theme.colors.cyan["300"] },
        { name: "IconChefHat", component: IconChefHat, hex: fullConfig.theme.colors.sky["500"] },
        { name: "IconMicrowave", component: IconMicrowave, hex: fullConfig.theme.colors.blue["300"] },
        { name: "IconDevices", component: IconDevices, hex: fullConfig.theme.colors.indigo["700"] },
        { name: "IconDevices2", component: IconDevices2, hex: fullConfig.theme.colors.violet["500"] },
        { name: "IconBolt", component: IconBolt, hex: fullConfig.theme.colors.purple["500"] },
        { name: "IconCpu", component: IconCpu, hex: fullConfig.theme.colors.fuchsia["700"] },
        { name: "IconBoxSeam", component: IconBoxSeam, hex: fullConfig.theme.colors.rose["500"] },
        { name: "IconMoodSmile", component: IconMoodSmile, hex: fullConfig.theme.colors.red["300"] },
        { name: "IconFish", component: IconFish, hex: fullConfig.theme.colors.orange["300"] },
        { name: "IconFridge", component: IconFridge, hex: fullConfig.theme.colors.yellow["500"] },
        { name: "IconGasStation", component: IconGasStation, hex: fullConfig.theme.colors.lime["300"] },
        { name: "IconRadio", component: IconRadio, hex: fullConfig.theme.colors.green["500"] },
        { name: "IconBarbell", component: IconBarbell, hex: fullConfig.theme.colors.emerald["700"] },
        { name: "IconThermometer", component: IconThermometer, hex: fullConfig.theme.colors.teal["700"] },
        { name: "IconBook", component: IconBook, hex: fullConfig.theme.colors.cyan["300"] },
        { name: "IconDeviceLaptop", component: IconDeviceLaptop, hex: fullConfig.theme.colors.sky["700"] },
        { name: "IconPigMoney", component: IconPigMoney, hex: fullConfig.theme.colors.blue["300"] },
        { name: "IconMotorbike", component: IconMotorbike, hex: fullConfig.theme.colors.indigo["300"] },
        { name: "IconBike", component: IconBike, hex: fullConfig.theme.colors.violet["700"] },
        { name: "IconPaint", component: IconPaint, hex: fullConfig.theme.colors.purple["700"] },
        {
            name: "IconBallAmericanFootball",
            component: IconBallAmericanFootball,
            hex: fullConfig.theme.colors.fuchsia["500"],
        },
        { name: "IconCut", component: IconCut, hex: fullConfig.theme.colors.rose["700"] },
        { name: "IconAerialLift", component: IconAerialLift, hex: fullConfig.theme.colors.red["700"] },
        { name: "IconSmoking", component: IconSmoking, hex: fullConfig.theme.colors.orange["700"] },
        { name: "IconSoccerField", component: IconSoccerField, hex: fullConfig.theme.colors.yellow["300"] },
        { name: "IconShoe", component: IconShoe, hex: fullConfig.theme.colors.lime["500"] },
        { name: "IconTrain", component: IconTrain, hex: fullConfig.theme.colors.green["300"] },
        { name: "IconSpeedboat", component: IconSpeedboat, hex: fullConfig.theme.colors.emerald["500"] },
        { name: "IconFlower", component: IconFlower, hex: fullConfig.theme.colors.teal["300"] },
        { name: "IconIceCream2", component: IconIceCream2, hex: fullConfig.theme.colors.cyan["700"] },
        { name: "IconEyeglass2", component: IconEyeglass2, hex: fullConfig.theme.colors.rose["700"] },
    ];
}
