import {
    IconReceipt2,
    IconCar,
    IconShirt,
    IconCoffee,
    IconPhone,
    IconToolsKitchen2,
    IconDeviceGamepad,
    IconPlaneTilt,
    IconShoppingCart,
    IconGift,
    IconFirstAidKit,
    IconBeach,
    IconHome2,
    IconMovie,
    IconDog,
    IconBallFootball,
    IconReceiptTax,
    IconToiletPaper,
    IconBus,
    IconBuilding,
} from "@tabler/icons-vue";

export function iconComponents() {
    return [
        { name: "IconReceipt2", component: IconReceipt2 },
        { name: "IconCar", component: IconCar },
        { name: "IconShirt", component: IconShirt },
        { name: "IconCoffee", component: IconCoffee },
        { name: "IconPhone", component: IconPhone },
        { name: "IconToolsKitchen2", component: IconToolsKitchen2 },
        { name: "IconDeviceGamepad", component: IconDeviceGamepad },
        { name: "IconPlaneTilt", component: IconPlaneTilt },
        { name: "IconShoppingCart", component: IconShoppingCart },
        { name: "IconGift", component: IconGift },
        { name: "IconFirstAidKit", component: IconFirstAidKit },
        { name: "IconBeach", component: IconBeach },
        { name: "IconHome2", component: IconHome2 },
        { name: "IconMovie", component: IconMovie },
        { name: "IconDog", component: IconDog },
        { name: "IconBallFootball", component: IconBallFootball },
        { name: "IconReceiptTax", component: IconReceiptTax },
        { name: "IconToiletPaper", component: IconToiletPaper },
        { name: "IconBus", component: IconBus },
        { name: "IconBuilding", component: IconBuilding },
    ];
}
