<?php

namespace App\Faker;

use Faker\Provider\Base;

// https://hofmannsven.com/2021/faker-provider-in-laravel
class ExpenseProvider extends Base
{
    protected static array $expenseNotes = [
        'Bills' => [
            'Internet bill',
            'Electricity payment',
            'Rent',
            'Water bill',
            'Gas bill',
            'Mobile phone bill',
            'Cable TV subscription',
            'Insurance payment',
            'Mortgage',
            'Trash collection fee',
            'Property tax',
            'Heating bill',
            'Car insurance',
            'Health insurance',
            'Credit card payment',
        ],

        'Car' => [
            'Gasoline',
            'Parking fee',
            'Car wash',
            'Oil change',
            'Tires replacement',
            'Brake repair',
            'Car registration',
            'Toll fees',
            'Windshield replacement',
            'Car detailing',
            'Engine tune-up',
            'Battery replacement',
            'Transmission fluid change',
            'Alignment service',
            'Air fresheners',
        ],

        'Clothes' => [
            'T-shirt purchase',
            'Jeans shopping',
            'Sneakers',
            'Winter coat',
            'Formal dress',
            'Running shoes',
            'Socks and underwear',
            'Hat and gloves',
            'Sunglasses',
            'Swimsuit',
            'Workout clothes',
            'Dress shoes',
            'Scarf',
            'Handbag',
            'Belt',
        ],

        'Coffee' => [
            'Espresso at local cafe',
            'Cappuccino at Starbucks',
            'Coffee beans purchase',
            'Latte from coffee shop',
            'Iced coffee',
            'Cold brew',
            'Coffee machine repair',
            'Coffee grinder',
            'Coffee subscription',
            'French press',
            'Coffee mug set',
            'Coffee filter refill',
            'Coffee travel tumbler',
            'Coffee table book',
            'Coffee scented candle',
        ],

        'Communications' => [
            'Mobile phone purchase',
            'Phone case',
            'Headphones',
            'Bluetooth speaker',
            'Internet router',
            'Webcam',
            'Microphone',
            'Laptop charger',
            'Phone charger cable',
            'Portable power bank',
            'Screen protector',
            'Laptop stand',
            'External hard drive',
            'Mouse and keyboard',
            'Laptop bag',
        ],

        'Eating out' => [
            'Dinner at a fancy restaurant',
            'Lunch at a local diner',
            'Fast food for lunch',
            'Pizza delivery',
            'Sushi takeout',
            'Brunch with friends',
            'Ice cream treat',
            'Food truck dinner',
            'Thai cuisine',
            'Indian restaurant',
            'Mexican food',
            'Chinese takeout',
            'BBQ night out',
            'Italian pasta dish',
            'Burger and fries',
        ],

        'Entertainment' => [
            'Movie theater tickets',
            'Concert tickets',
            'Video game purchase',
            'Board game',
            'Streaming service subscription',
            'Books and novels',
            'Art exhibition entry',
            'Theme park visit',
            'Escape room experience',
            'Amusement park tickets',
            'Comedy show tickets',
            'Karaoke night',
            'Virtual reality game',
            'Laser tag session',
            'Bowling night',
        ],

        'Flights' => [
            'Domestic flight ticket',
            'International flight ticket',
            'Airport parking',
            'In-flight snacks',
            'Luggage purchase',
            'TSA pre-check fee',
            'Airport lounge access',
            'Travel insurance',
            'Passport renewal',
            'Visas application fees',
            'Airport transfer',
            'Checked baggage fee',
            'Airline seat selection',
            'Airline miles upgrade',
            'Jet lag remedy',
        ],

        'Food' => [
            'Grocery shopping',
            'Farmers\' market produce',
            'Organic food purchase',
            'Specialty cheese',
            'Fresh seafood',
            'Gourmet chocolates',
            'Wine and spirits',
            'Cooking class fee',
            'Recipe ingredients',
            'Meal kit subscription',
            'Farmers\' market visit',
            'Dinner party supplies',
            'Grill and BBQ tools',
            'Specialty spices',
            'Cooking utensils',
        ],

        'Gifts' => [
            'Birthday',
            'Anniversary',
            'Wedding',
            'Baby shower',
            'Graduation',
            'Christmas',
            'Valentine\'s Day',
            'Mother\'s Day',
            'Father\'s Day',
            'Easter',
            'Halloween',
            'Thanksgiving',
            'Housewarming',
            'Retirement',
            'Get well soon',
        ],

        'Health' => [
            'Gym membership',
            'Fitness class',
            'Sports equipment',
            'Running shoes',
            'Vitamins and supplements',
            'Doctor\'s appointment',
            'Prescription medications',
            'Dental checkup',
            'Eye exam',
            'Health insurance premium',
            'Massage therapy',
            'Yoga class',
            'Mental health counseling',
            'Weight loss program',
            'Alternative medicine',
        ],

        'Holidays' => [
            'Hotel accommodation',
            'Resort stay',
            'Sightseeing tour',
            'Cruise vacation',
            'Souvenirs and gifts',
            'Travel gear and accessories',
            'Travel insurance',
            'Vacation rental',
            'Theme park tickets',
            'Beach essentials',
            'Ski trip expenses',
            'Adventure activities',
            'Travel vaccinations',
            'Pet boarding',
            'Camping gear',
        ],

        'House' => [
            'Furniture purchase',
            'Home decor items',
            'Appliance replacement',
            'Home improvement supplies',
            'Lawn care services',
            'Pest control',
            'Cleaning supplies',
            'Utility bills',
            'Home security system',
            'HVAC maintenance',
            'Plumbing services',
            'DIY project materials',
            'Home insurance',
            'Property tax',
            'Mortgage payment',
        ],

        'Movies' => [
            'Movie theater tickets',
            'Popcorn and snacks',
            'Streaming service subscription',
            'Blu-ray or DVD purchase',
            'Movie poster or memorabilia',
            'Home theater system',
            'Movie night snacks',
            'Redbox rental',
            'Movie rental subscription',
            'Collector\'s edition release',
            'Classic film screening',
            'Film festival tickets',
            'Movie merchandise',
            'Director\'s cut edition',
            'Soundtrack purchase',
        ],

        'Pets' => [
            'Pet food and treats',
            'Veterinary care',
            'Pet grooming',
            'Toys and accessories',
            'Pet insurance',
            'Pet boarding',
            'Litter and litter box',
            'Pet bed and blankets',
            'Collar and leash',
            'Training classes',
            'Pet medication',
            'Pet dental care',
            'Pet clothing',
            'Pet ID tag',
            'Pet carrier',
        ],

        'Sports' => [
            'Sports equipment',
            'Gym membership',
            'Fitness class',
            'Sports apparel',
            'Running shoes',
            'Outdoor adventure gear',
            'Sports event tickets',
            'Athletic competition entry fee',
            'Personal trainer sessions',
            'Team sports registration',
            'Sports league fees',
            'Fitness tracker',
            'Cycling accessories',
            'Hiking gear',
            'Swimming lessons',
        ],

        'Taxes' => [
            'Income tax preparation fee',
            'Tax software purchase',
            'Accounting services',
            'Tax consultation fee',
            'Business tax filing fee',
            'Property tax payment',
            'Sales tax payment',
            'Tax deductible expenses',
            'Tax filing extension fee',
            'Tax penalty payment',
            'Tax audit representation',
            'Tax refund processing fee',
            'State tax payment',
            'Federal tax payment',
            'Tax planning services',
        ],

        'Toiletry' => [
            'Shampoo and conditioner',
            'Body wash and soap',
            'Toothbrush and toothpaste',
            'Deodorant',
            'Shaving cream and razor',
            'Feminine hygiene products',
            'Hair styling products',
            'Skincare products',
            'Sunscreen',
            'Towel and washcloth',
            'Bathrobe',
            'Cotton swabs and pads',
            'Nail care items',
            'Hairdryer',
            'Candles and scents',
        ],

        'Transport' => [
            'Public transportation fare',
            'Gasoline',
            'Car rental',
            'Uber or Lyft ride',
            'Bicycle purchase',
            'Motorcycle gear',
            'Parking fee',
            'Toll fees',
            'Electric scooter rental',
            'Train tickets',
            'Boat or ferry ride',
            'Airport transfer',
            'Scooter accessories',
            'Bus pass',
            'Car maintenance',
        ],

        'Work Expenses' => [
            'Office supplies',
            'Business travel expenses',
            'Conference registration fee',
            'Professional development course',
            'Business meals and entertainment',
            'Business software subscription',
            'Work-related books',
            'Business attire',
            'Networking event fee',
            'Business insurance',
            'Trade show booth rental',
            'Office furniture purchase',
            'Business association membership',
            'Marketing materials',
            'Business card printing',
        ],

        // Add more categories as needed
    ];

    public function expenseNote(?string $category = null): string
    {
        if ($category !== null && array_key_exists($category, static::$expenseNotes)) {
            // If the provided category exists, return a random note from that category
            $randomExpenseNote = static::$expenseNotes[$category][array_rand(static::$expenseNotes[$category])];
        } else {
            // Otherwise, return a random note from the full list
            $flattenedNotes = array_reduce(static::$expenseNotes, 'array_merge', []);
            $randomExpenseNote = $flattenedNotes[array_rand($flattenedNotes)];
        }

        return $randomExpenseNote;
    }
}
