<?php

return [
    'default_categories' => [
        [ "name" => "Bills", "icon" => "bills", "hex" => "#ff0000"],
        [ "name" => "Car", "icon" => "car", "hex" => "#ff0000"],
        [ "name" => "Clothes", "icon" => "clothes", "hex" => "#ff0000"],
        [ "name" => "Coffee", "icon" => "coffee", "hex" => "#ff0000"],
        [ "name" => "Communications", "icon" => "communications", "hex" => "#ff0000"],
        [ "name" => "Eating out", "icon" => "eating-out", "hex" => "#ff0000"],
        [ "name" => "Entertainment", "icon" => "entertainment", "hex" => "#ff0000"],
        [ "name" => "Flights", "icon" => "flights", "hex" => "#ff0000"],
        [ "name" => "Food", "icon" => "food", "hex" => "#ff0000"],
        [ "name" => "Gifts", "icon" => "gifts", "hex" => "#ff0000"],
        [ "name" => "Health", "icon" => "health", "hex" => "#ff0000"],
        [ "name" => "Holidays", "icon" => "holidays", "hex" => "#ff0000"],
        [ "name" => "House", "icon" => "house", "hex" => "#ff0000"],
        [ "name" => "Movies", "icon" => "movies", "hex" => "#ff0000"],
        [ "name" => "Pets", "icon" => "pets", "hex" => "#ff0000"],
        [ "name" => "Sports", "icon" => "sports", "hex" => "#ff0000"],
        [ "name" => "Taxes", "icon" => "taxes", "hex" => "#ff0000"],
        [ "name" => "Toiletry", "icon" => "toiletry", "hex" => "#ff0000"],
        [ "name" => "Transport", "icon" => "transport", "hex" => "#ff0000"],
        [ "name" => "Work Expenses", "icon" => "work-expenses", "hex" => "#ff0000"],
    ],
    'category_icons' => [
        'bills',
        'car',
        'clothes',
        'coffee',
        'communications',
        'eating-out',
        'entertainment',
        'flights',
        'food',
        'gifts',
        'health',
        'holidays',
        'house',
        'movies',
        'pets',
        'sports',
        'taxes',
        'toiletry',
        'transport',
        'work-expenses',
    ],
];

